//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Vector2 p_default_Move;
        
        private static SteamVR_Action_Vector2 p_default_RadialSelect;
        
        private static SteamVR_Action_Boolean p_default_Confirm;
        
        private static SteamVR_Action_Boolean p_default_Cancel;
        
        private static SteamVR_Action_Boolean p_default_Accept;
        
        private static SteamVR_Action_Boolean p_default_RadialSelectShow;
        
        private static SteamVR_Action_Boolean p_default_DiscardItem;
        
        private static SteamVR_Action_Boolean p_default_DoAbility;
        
        private static SteamVR_Action_Boolean p_default_Interact;
        
        private static SteamVR_Action_Boolean p_default_Reel;
        
        private static SteamVR_Action_Boolean p_default_SellItem;
        
        private static SteamVR_Action_Boolean p_default_RotateClockwise;
        
        private static SteamVR_Action_Boolean p_default_RotateCounterClockwise;
        
        private static SteamVR_Action_Boolean p_default_ToggleCargo;
        
        private static SteamVR_Action_Boolean p_default_Pause;
        
        private static SteamVR_Action_Boolean p_default_BuyItem;
        
        private static SteamVR_Action_Boolean p_default_RepairItem;
        
        private static SteamVR_Action_Boolean p_default_RepairAll;
        
        private static SteamVR_Action_Boolean p_default_RepairMode;
        
        private static SteamVR_Action_Boolean p_default_ZoomMapIn;
        
        private static SteamVR_Action_Boolean p_default_ZoomMapOut;
        
        private static SteamVR_Action_Boolean p_default_RemoveMarker;
        
        private static SteamVR_Action_Pose p_default_LeftHandPose;
        
        private static SteamVR_Action_Pose p_default_RightHandPose;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_Move
        {
            get
            {
                return SteamVR_Actions.p_default_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_RadialSelect
        {
            get
            {
                return SteamVR_Actions.p_default_RadialSelect.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Confirm
        {
            get
            {
                return SteamVR_Actions.p_default_Confirm.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Cancel
        {
            get
            {
                return SteamVR_Actions.p_default_Cancel.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Accept
        {
            get
            {
                return SteamVR_Actions.p_default_Accept.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RadialSelectShow
        {
            get
            {
                return SteamVR_Actions.p_default_RadialSelectShow.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DiscardItem
        {
            get
            {
                return SteamVR_Actions.p_default_DiscardItem.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DoAbility
        {
            get
            {
                return SteamVR_Actions.p_default_DoAbility.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Interact
        {
            get
            {
                return SteamVR_Actions.p_default_Interact.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Reel
        {
            get
            {
                return SteamVR_Actions.p_default_Reel.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SellItem
        {
            get
            {
                return SteamVR_Actions.p_default_SellItem.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RotateClockwise
        {
            get
            {
                return SteamVR_Actions.p_default_RotateClockwise.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RotateCounterClockwise
        {
            get
            {
                return SteamVR_Actions.p_default_RotateCounterClockwise.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ToggleCargo
        {
            get
            {
                return SteamVR_Actions.p_default_ToggleCargo.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Pause
        {
            get
            {
                return SteamVR_Actions.p_default_Pause.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_BuyItem
        {
            get
            {
                return SteamVR_Actions.p_default_BuyItem.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RepairItem
        {
            get
            {
                return SteamVR_Actions.p_default_RepairItem.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RepairAll
        {
            get
            {
                return SteamVR_Actions.p_default_RepairAll.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RepairMode
        {
            get
            {
                return SteamVR_Actions.p_default_RepairMode.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ZoomMapIn
        {
            get
            {
                return SteamVR_Actions.p_default_ZoomMapIn.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ZoomMapOut
        {
            get
            {
                return SteamVR_Actions.p_default_ZoomMapOut.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_RemoveMarker
        {
            get
            {
                return SteamVR_Actions.p_default_RemoveMarker.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_LeftHandPose
        {
            get
            {
                return SteamVR_Actions.p_default_LeftHandPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose default_RightHandPose
        {
            get
            {
                return SteamVR_Actions.p_default_RightHandPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_RadialSelect,
                    SteamVR_Actions.default_Confirm,
                    SteamVR_Actions.default_Cancel,
                    SteamVR_Actions.default_Accept,
                    SteamVR_Actions.default_RadialSelectShow,
                    SteamVR_Actions.default_DiscardItem,
                    SteamVR_Actions.default_DoAbility,
                    SteamVR_Actions.default_Interact,
                    SteamVR_Actions.default_Reel,
                    SteamVR_Actions.default_SellItem,
                    SteamVR_Actions.default_RotateClockwise,
                    SteamVR_Actions.default_RotateCounterClockwise,
                    SteamVR_Actions.default_ToggleCargo,
                    SteamVR_Actions.default_Pause,
                    SteamVR_Actions.default_BuyItem,
                    SteamVR_Actions.default_RepairItem,
                    SteamVR_Actions.default_RepairAll,
                    SteamVR_Actions.default_RepairMode,
                    SteamVR_Actions.default_ZoomMapIn,
                    SteamVR_Actions.default_ZoomMapOut,
                    SteamVR_Actions.default_RemoveMarker,
                    SteamVR_Actions.default_LeftHandPose,
                    SteamVR_Actions.default_RightHandPose,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_RadialSelect,
                    SteamVR_Actions.default_Confirm,
                    SteamVR_Actions.default_Cancel,
                    SteamVR_Actions.default_Accept,
                    SteamVR_Actions.default_RadialSelectShow,
                    SteamVR_Actions.default_DiscardItem,
                    SteamVR_Actions.default_DoAbility,
                    SteamVR_Actions.default_Interact,
                    SteamVR_Actions.default_Reel,
                    SteamVR_Actions.default_SellItem,
                    SteamVR_Actions.default_RotateClockwise,
                    SteamVR_Actions.default_RotateCounterClockwise,
                    SteamVR_Actions.default_ToggleCargo,
                    SteamVR_Actions.default_Pause,
                    SteamVR_Actions.default_BuyItem,
                    SteamVR_Actions.default_RepairItem,
                    SteamVR_Actions.default_RepairAll,
                    SteamVR_Actions.default_RepairMode,
                    SteamVR_Actions.default_ZoomMapIn,
                    SteamVR_Actions.default_ZoomMapOut,
                    SteamVR_Actions.default_RemoveMarker,
                    SteamVR_Actions.default_LeftHandPose,
                    SteamVR_Actions.default_RightHandPose,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_LeftHandPose,
                    SteamVR_Actions.default_RightHandPose,
                    SteamVR_Actions.mixedreality_ExternalCamera};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_Confirm,
                    SteamVR_Actions.default_Cancel,
                    SteamVR_Actions.default_Accept,
                    SteamVR_Actions.default_RadialSelectShow,
                    SteamVR_Actions.default_DiscardItem,
                    SteamVR_Actions.default_DoAbility,
                    SteamVR_Actions.default_Interact,
                    SteamVR_Actions.default_Reel,
                    SteamVR_Actions.default_SellItem,
                    SteamVR_Actions.default_RotateClockwise,
                    SteamVR_Actions.default_RotateCounterClockwise,
                    SteamVR_Actions.default_ToggleCargo,
                    SteamVR_Actions.default_Pause,
                    SteamVR_Actions.default_BuyItem,
                    SteamVR_Actions.default_RepairItem,
                    SteamVR_Actions.default_RepairAll,
                    SteamVR_Actions.default_RepairMode,
                    SteamVR_Actions.default_ZoomMapIn,
                    SteamVR_Actions.default_ZoomMapOut,
                    SteamVR_Actions.default_RemoveMarker,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.buggy_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_RadialSelect,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Move,
                    SteamVR_Actions.default_RadialSelect,
                    SteamVR_Actions.default_Confirm,
                    SteamVR_Actions.default_Cancel,
                    SteamVR_Actions.default_Accept,
                    SteamVR_Actions.default_RadialSelectShow,
                    SteamVR_Actions.default_DiscardItem,
                    SteamVR_Actions.default_DoAbility,
                    SteamVR_Actions.default_Interact,
                    SteamVR_Actions.default_Reel,
                    SteamVR_Actions.default_SellItem,
                    SteamVR_Actions.default_RotateClockwise,
                    SteamVR_Actions.default_RotateCounterClockwise,
                    SteamVR_Actions.default_ToggleCargo,
                    SteamVR_Actions.default_Pause,
                    SteamVR_Actions.default_BuyItem,
                    SteamVR_Actions.default_RepairItem,
                    SteamVR_Actions.default_RepairAll,
                    SteamVR_Actions.default_RepairMode,
                    SteamVR_Actions.default_ZoomMapIn,
                    SteamVR_Actions.default_ZoomMapOut,
                    SteamVR_Actions.default_RemoveMarker,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Move")));
            SteamVR_Actions.p_default_RadialSelect = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/RadialSelect")));
            SteamVR_Actions.p_default_Confirm = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Confirm")));
            SteamVR_Actions.p_default_Cancel = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Cancel")));
            SteamVR_Actions.p_default_Accept = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Accept")));
            SteamVR_Actions.p_default_RadialSelectShow = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RadialSelectShow")));
            SteamVR_Actions.p_default_DiscardItem = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DiscardItem")));
            SteamVR_Actions.p_default_DoAbility = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DoAbility")));
            SteamVR_Actions.p_default_Interact = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Interact")));
            SteamVR_Actions.p_default_Reel = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Reel")));
            SteamVR_Actions.p_default_SellItem = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SellItem")));
            SteamVR_Actions.p_default_RotateClockwise = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RotateClockwise")));
            SteamVR_Actions.p_default_RotateCounterClockwise = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RotateCounterClockwise")));
            SteamVR_Actions.p_default_ToggleCargo = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ToggleCargo")));
            SteamVR_Actions.p_default_Pause = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Pause")));
            SteamVR_Actions.p_default_BuyItem = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/BuyItem")));
            SteamVR_Actions.p_default_RepairItem = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RepairItem")));
            SteamVR_Actions.p_default_RepairAll = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RepairAll")));
            SteamVR_Actions.p_default_RepairMode = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RepairMode")));
            SteamVR_Actions.p_default_ZoomMapIn = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ZoomMapIn")));
            SteamVR_Actions.p_default_ZoomMapOut = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ZoomMapOut")));
            SteamVR_Actions.p_default_RemoveMarker = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/RemoveMarker")));
            SteamVR_Actions.p_default_LeftHandPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/LeftHandPose")));
            SteamVR_Actions.p_default_RightHandPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/RightHandPose")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
        }
    }
}
