//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftGrab
        {
            get
            {
                return SteamVR_Actions.default_LeftGrab;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightGrab
        {
            get
            {
                return SteamVR_Actions.default_RightGrab;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTrigger
        {
            get
            {
                return SteamVR_Actions.default_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrigger
        {
            get
            {
                return SteamVR_Actions.default_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHandPose
        {
            get
            {
                return SteamVR_Actions.default_LeftHandPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHandPose
        {
            get
            {
                return SteamVR_Actions.default_RightHandPose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftThumbStick
        {
            get
            {
                return SteamVR_Actions.default_LeftThumbStick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightThumbStick
        {
            get
            {
                return SteamVR_Actions.default_RightThumbStick;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Left
        {
            get
            {
                return SteamVR_Actions.default_B_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Left
        {
            get
            {
                return SteamVR_Actions.default_A_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Right
        {
            get
            {
                return SteamVR_Actions.default_B_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Right
        {
            get
            {
                return SteamVR_Actions.default_A_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftStart
        {
            get
            {
                return SteamVR_Actions.default_LeftStart;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftThumbStickPress
        {
            get
            {
                return SteamVR_Actions.default_LeftThumbStickPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightThumbStickPress
        {
            get
            {
                return SteamVR_Actions.default_RightThumbStickPress;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
