//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RadialSelect
        {
            get
            {
                return SteamVR_Actions.default_RadialSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean Confirm
        {
            get
            {
                return SteamVR_Actions.default_Confirm;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cancel
        {
            get
            {
                return SteamVR_Actions.default_Cancel;
            }
        }
        
        public virtual SteamVR_Action_Boolean Accept
        {
            get
            {
                return SteamVR_Actions.default_Accept;
            }
        }
        
        public virtual SteamVR_Action_Boolean RadialSelectShow
        {
            get
            {
                return SteamVR_Actions.default_RadialSelectShow;
            }
        }
        
        public virtual SteamVR_Action_Boolean DiscardItem
        {
            get
            {
                return SteamVR_Actions.default_DiscardItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean DoAbility
        {
            get
            {
                return SteamVR_Actions.default_DoAbility;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.default_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reel
        {
            get
            {
                return SteamVR_Actions.default_Reel;
            }
        }
        
        public virtual SteamVR_Action_Boolean SellItem
        {
            get
            {
                return SteamVR_Actions.default_SellItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateClockwise
        {
            get
            {
                return SteamVR_Actions.default_RotateClockwise;
            }
        }
        
        public virtual SteamVR_Action_Boolean RotateCounterClockwise
        {
            get
            {
                return SteamVR_Actions.default_RotateCounterClockwise;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleCargo
        {
            get
            {
                return SteamVR_Actions.default_ToggleCargo;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pause
        {
            get
            {
                return SteamVR_Actions.default_Pause;
            }
        }
        
        public virtual SteamVR_Action_Boolean BuyItem
        {
            get
            {
                return SteamVR_Actions.default_BuyItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean RepairItem
        {
            get
            {
                return SteamVR_Actions.default_RepairItem;
            }
        }
        
        public virtual SteamVR_Action_Boolean RepairAll
        {
            get
            {
                return SteamVR_Actions.default_RepairAll;
            }
        }
        
        public virtual SteamVR_Action_Boolean RepairMode
        {
            get
            {
                return SteamVR_Actions.default_RepairMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomMapIn
        {
            get
            {
                return SteamVR_Actions.default_ZoomMapIn;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomMapOut
        {
            get
            {
                return SteamVR_Actions.default_ZoomMapOut;
            }
        }
        
        public virtual SteamVR_Action_Boolean RemoveMarker
        {
            get
            {
                return SteamVR_Actions.default_RemoveMarker;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHandPose
        {
            get
            {
                return SteamVR_Actions.default_LeftHandPose;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHandPose
        {
            get
            {
                return SteamVR_Actions.default_RightHandPose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
